<script lang="ts">
  let year = 2023;
</script>

<p><a href="https://adventofcode.com">Advent of Code</a> is an advent calendar
comprised of programming puzzles. This is an unofficial alternate comparison
mechanism that uses solution runtime time instead of the default
time-to-submission ranking.</p>

<p>These benchmarks are generated by a
<a href="http://ci.papercode.net:8080/teams/main/pipelines/aoc{year}">CI pipeline</a>
running on relatively dedicated hardware. Participant solutions are run against
a variety of valid inputs, with the goal of correcting for differences in input
complexity and speed individual hardware.</p>

<p>The benchmarks themselves are computed using
<a href="https://github.com/sharkdp/hyperfine">hyperfine</a>, which has the
effect of testing the entirety of program startup, reading the input from disk,
and computing the solution. As such, there is high variance for times less than
5 ms, as per the hyperfine documentation, as a not insignificant part of that is
shell startup time.</p>
