platform: linux
image_resource:
  type: registry-image
  source:
    repository: curlimages/curl
    tag: "8.1.2"

inputs:
  - name: repo

outputs:
  - name: image-tags

params:
  IMAGE_REPO:

run:
  path: repo/ci/scripts/extract-version-tags.sh
  user: root
